---
title: 'The importance of reproducible research'
author: "Gabriel Nakamura"
date: "5/17/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

In this section you will find a few articles on the importance of adopting a reproducible workflow in your research project. From the individual perspective reproducibility helps you with self-organization. From the research community perspective reproducibility helps everyone to push forward the boundaries of science by facilitation the colaboration. This article is a good source of information that list some [relevant reasons to addopt a reproducible workflow](https://esajournals.onlinelibrary.wiley.com/doi/10.1002/bes2.1801). 

# Suggested literature

- [Perkel, Jeffrey. Democratic databases: Science on GitHub. 2016. Nature](https://www.nature.com/news/democratic-databases-science-on-github-1.20719)
- [Five concrete reasons your students should be learning to analyzing data in a reproducible way](https://chance.amstat.org/2014/09/reproducible-paradigm/)
- [Publish your computer code: it is good enough](https://www.nature.com/news/2010/101013/pdf/467753a.pdf)
- [Not just for programmers: How github can accelerate collaborative and reproducible research in ecology and evolution](https://www.researchgate.net/publication/361991379_Not_just_for_programmers_How_GitHub_can_accelerate_collaborative_and_reproducible_research_in_ecology_and_evolution)
- [A begginers guide to conducting reproducible research](https://esajournals.onlinelibrary.wiley.com/doi/10.1002/bes2.1801)  
- [Happy git with R](https://happygitwithr.com/index.html) This is the best one in my opinion!


